# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  sam-edmp

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  ConnTableName:
    Type: String
    Default: 'connections'
    Description: (Required) The name of the new DynamoDB to store connection information. Minimum 3 characters
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z_]+$
    ConstraintDescription: 'Required. Can be characters and underscore only. No numbers or special characters allowed.'
  TraceTableName:
    Type: String
    Default: 'traces'
    Description: (Required) The name of the new DynamoDB to store user trace information. Minimum 3 characters
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z_]+$
    ConstraintDescription: 'Required. Can be characters and underscore only. No numbers or special characters allowed.'
  OfferTableName:
    Type: String
    Default: 'offers'
    Description: (Required) The name of the new DynamoDB to store trade information. Minimum 3 characters
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z_]+$
    ConstraintDescription: 'Required. Can be characters and underscore only. No numbers or special characters allowed.'

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  EDMarketplaceSocket:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: EDMarketplaceSocket
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"
  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref EDMarketplaceSocket
      RouteKey: $connect
      AuthorizationType: NONE
      OperationName: ConnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref ConnectInteg
  ConnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref EDMarketplaceSocket
      Description: Connect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnConnectFunction.Arn}/invocations
  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref EDMarketplaceSocket
      RouteKey: $disconnect
      AuthorizationType: NONE
      OperationName: DisconnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref DisconnectInteg
  DisconnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref EDMarketplaceSocket
      Description: Disconnect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnDisconnectFunction.Arn}/invocations
  OfferRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref EDMarketplaceSocket
      RouteKey: offer
      AuthorizationType: NONE
      OperationName: OfferRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref OfferInteg
  OfferInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref EDMarketplaceSocket
      Description: Offer Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OfferFunction.Arn}/invocations
  CommsRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref EDMarketplaceSocket
      RouteKey: comms
      AuthorizationType: NONE
      OperationName: CommsRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref CommsInteg
  CommsInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref EDMarketplaceSocket
      Description: Comms Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CommsFunction.Arn}/invocations

  # Deployment
  Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
    - ConnectRoute
    - OfferRoute
    - CommsRoute
    - DisconnectRoute
    Properties:
      ApiId: !Ref EDMarketplaceSocket
  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: Prod
      Description: Prod Stage
      DeploymentId: !Ref Deployment
      ApiId: !Ref EDMarketplaceSocket

  # Tables

  # Connections table
  ConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: "connectionId"
        AttributeType: "S"
      KeySchema:
      - AttributeName: "connectionId"
        KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      SSESpecification:
        SSEEnabled: True
      TableName: !Ref ConnTableName

  # Traces table
  TracesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: "token"
        AttributeType: "S"
      KeySchema:
      - AttributeName: "token"
        KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      SSESpecification:
        SSEEnabled: True
      TableName: !Ref TraceTableName

  # Offers table
  OffersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: "offerId"
        AttributeType: "S"
      KeySchema:
      - AttributeName: "offerId"
        KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      SSESpecification:
        SSEEnabled: True
      TableName: !Ref OfferTableName

  # Function: OnConnect
  OnConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/on-connect.onConnect
      MemorySize: 256
      Runtime: nodejs14.x
      Timeout: 50
      Description: A Lambda function that handles connection of a user.
      Environment:
        Variables:
          CONN_TABLE_NAME: !Ref ConnTableName
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref ConnTableName
      - Statement:
        - Effect: Allow
          Action:
          - 'execute-api:ManageConnections'
          Resource:
          - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${EDMarketplaceSocket}/*'
  OnConnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - EDMarketplaceSocket
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OnConnectFunction
      Principal: apigateway.amazonaws.com

  # Function: OnDisconnect
  OnDisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/on-disconnect.onDisconnect
      MemorySize: 256
      Runtime: nodejs14.x
      Timeout: 50
      Description: A Lambda function that handles disconnection of a user.
      Environment:
        Variables:
          CONN_TABLE_NAME: !Ref ConnTableName
          TRACE_TABLE_NAME: !Ref TraceTableName
          OFFER_TABLE_NAME: !Ref OfferTableName
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref ConnTableName
      - DynamoDBCrudPolicy:
          TableName: !Ref TraceTableName
      - DynamoDBCrudPolicy:
          TableName: !Ref OfferTableName
      - Statement:
        - Effect: Allow
          Action:
          - 'execute-api:ManageConnections'
          Resource:
          - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${EDMarketplaceSocket}/*'
  OnDisconnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - EDMarketplaceSocket
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OnDisconnectFunction
      Principal: apigateway.amazonaws.com

  # Function: Offer
  OfferFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/offer.offer
      MemorySize: 256
      Runtime: nodejs14.x
      Timeout: 50
      Description: A Lambda function that process actions related to offers (publish, get list, remove).
      Environment:
        Variables:
          CONN_TABLE_NAME: !Ref ConnTableName
          TRACE_TABLE_NAME: !Ref TraceTableName
          OFFER_TABLE_NAME: !Ref OfferTableName
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref ConnTableName
      - DynamoDBCrudPolicy:
          TableName: !Ref TraceTableName
      - DynamoDBCrudPolicy:
          TableName: !Ref OfferTableName
      - Statement:
        - Effect: Allow
          Action:
          - 'execute-api:ManageConnections'
          Resource:
          - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${EDMarketplaceSocket}/*'
  OfferPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - EDMarketplaceSocket
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OfferFunction
      Principal: apigateway.amazonaws.com

  # Function: Comms
  CommsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/comms.comms
      MemorySize: 256
      Runtime: nodejs14.x
      Timeout: 50
      Description: A Lambda function that process actions related to communications between parties (bids, messages).
      Environment:
        Variables:
          CONN_TABLE_NAME: !Ref ConnTableName
          TRACE_TABLE_NAME: !Ref TraceTableName
          OFFER_TABLE_NAME: !Ref OfferTableName
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref ConnTableName
      - DynamoDBCrudPolicy:
          TableName: !Ref TraceTableName
      - DynamoDBCrudPolicy:
          TableName: !Ref OfferTableName
      - Statement:
        - Effect: Allow
          Action:
          - 'execute-api:ManageConnections'
          Resource:
          - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${EDMarketplaceSocket}/*'
  CommsPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - EDMarketplaceSocket
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref CommsFunction
      Principal: apigateway.amazonaws.com

# Outputs
Outputs:
  ConnectionsTableArn:
    Description: "Connections Table ARN"
    Value: !GetAtt ConnectionsTable.Arn

  TracesTableArn:
    Description: "Traces Table ARN"
    Value: !GetAtt TracesTable.Arn

  OffersTableArn:
    Description: "Offers Table ARN"
    Value: !GetAtt OffersTable.Arn

  OnConnectFunctionArn:
    Description: "OnConnect function ARN"
    Value: !GetAtt OnConnectFunction.Arn

  OnDisconnectFunctionArn:
    Description: "OnDisconnect function ARN"
    Value: !GetAtt OnDisconnectFunction.Arn

  OfferFunctionArn:
    Description: "Offer handler function ARN"
    Value: !GetAtt OfferFunction.Arn

  CommsFunctionArn:
    Description: "Comms handler function ARN"
    Value: !GetAtt CommsFunction.Arn

  WebSocketURI:
    Description: "The WSS Protocol URI to connect to"
    Value: !Join [ '', [ 'wss://', !Ref EDMarketplaceSocket, '.execute-api.',!Ref 'AWS::Region','.amazonaws.com/',!Ref 'Stage'] ]

